language: go

go:
    - "1.6.2"

env:
    global:
        - SSH_KEY="id_rsa_github"
        - GIT_NAME="roll"
        - GIT_EMAIL="github@rollxx.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="master"

before_install:
    - openssl aes-256-cbc -K $encrypted_5badef0aa7c9_key -iv $encrypted_5badef0aa7c9_iv -in id_rsa_github.enc -out id_rsa_github -d

before_script:
    - go get -u -v github.com/spf13/hugo

script:
    - hugo

after_success:
    - ./deploy.sh
