language: go

install: go get -v github.com/spf13/hugo

env:
    global:
        - SSH_KEY="id_rsa_github"
        - GIT_NAME="roll"
        - GIT_EMAIL="github@rollxx.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="master"

before_install:
    - openssl aes-256-cbc -K $encrypted_c9ce2f6b7e47_key -iv $encrypted_c9ce2f6b7e47_iv -in id_rsa_github.enc -out id_rsa_github -d
    - chmod 600 $SSH_KEY
    - eval `ssh-agent -s`
    - ssh-add $SSH_KEY

script:
    - hugo

after_success:
    - ./deploy.sh
